namespace D3dxSkinManager.Modules.System.Models;

/// <summary>
/// Auto-update manifest: the list of updatable files shipped with a release (generated by
/// devtools/scripts/build-manifest.mjs). Diffing the installed manifest against a release's manifest
/// yields the added / updated / removed files the updater must apply. The launcher exe is never listed
/// (it does not auto-update). See docs/LAUNCHER_ARCHITECTURE.md.
/// </summary>
public class UpdateManifest
{
    public string Version { get; set; } = string.Empty;
    public string GeneratedAt { get; set; } = string.Empty;
    public List<ManifestFile> Files { get; set; } = new();
}

/// <summary>One file entry in an <see cref="UpdateManifest"/>.</summary>
public class ManifestFile
{
    /// <summary>Relative path from the install root, forward-slash separated.</summary>
    public string Path { get; set; } = string.Empty;
    public long Size { get; set; }
    public string Sha256 { get; set; } = string.Empty;
}

/// <summary>How a single file changes between the installed manifest and a release manifest.</summary>
public enum ManifestChangeKind
{
    Added,
    Updated,
    Removed,
}

/// <summary>A single file delta in a <see cref="ManifestDiff"/>.</summary>
public class ManifestChange
{
    public string Path { get; set; } = string.Empty;
    public ManifestChangeKind Kind { get; set; }
    /// <summary>Bytes to download for this change (the new file size; 0 for a removal).</summary>
    public long Size { get; set; }
}

/// <summary>
/// The set of changes to turn an installed manifest into a target (release) manifest.
/// </summary>
public class ManifestDiff
{
    public List<ManifestChange> Added { get; set; } = new();
    public List<ManifestChange> Updated { get; set; } = new();
    public List<ManifestChange> Removed { get; set; } = new();

    /// <summary>True when nothing changed (installed already matches the target).</summary>
    public bool IsEmpty => Added.Count == 0 && Updated.Count == 0 && Removed.Count == 0;

    /// <summary>Total files touched (added + updated + removed).</summary>
    public int ChangedFileCount => Added.Count + Updated.Count + Removed.Count;

    /// <summary>Total bytes to download (added + updated; removals download nothing).</summary>
    public long DownloadSize =>
        Added.Sum(c => c.Size) + Updated.Sum(c => c.Size);

    /// <summary>
    /// Compute the diff from <paramref name="installed"/> to <paramref name="target"/>.
    /// Added = in target not installed; Updated = in both, sha256 differs; Removed = in installed
    /// not target. Pure function — no I/O.
    /// </summary>
    public static ManifestDiff Compute(UpdateManifest installed, UpdateManifest target)
    {
        var diff = new ManifestDiff();

        var installedByPath = installed.Files.ToDictionary(f => f.Path, StringComparer.OrdinalIgnoreCase);
        var targetPaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var tf in target.Files)
        {
            targetPaths.Add(tf.Path);
            if (!installedByPath.TryGetValue(tf.Path, out var existing))
            {
                diff.Added.Add(new ManifestChange { Path = tf.Path, Kind = ManifestChangeKind.Added, Size = tf.Size });
            }
            else if (!string.Equals(existing.Sha256, tf.Sha256, StringComparison.OrdinalIgnoreCase))
            {
                diff.Updated.Add(new ManifestChange { Path = tf.Path, Kind = ManifestChangeKind.Updated, Size = tf.Size });
            }
        }

        foreach (var inf in installed.Files)
        {
            if (!targetPaths.Contains(inf.Path))
            {
                diff.Removed.Add(new ManifestChange { Path = inf.Path, Kind = ManifestChangeKind.Removed, Size = 0 });
            }
        }

        return diff;
    }
}
